/**
 * Strip Conductor-injected boilerplate from the *start* of a user message so
 * the real prompt becomes the session title / timeline content.
 *
 * Conductor prepends one or more instruction blocks to the first user message:
 *
 *   <system_instruction> You are working inside Conductor... </system_instruction>
 *   <system-instruction> To do immediately: rename the branch... </system-instruction>
 *   /tmp/attachments/pasted_text_....txt
 *   <the actual user ask>
 *
 * We only remove blocks that are *anchored at the start* and have a matching
 * close tag, so a genuine mid-conversation mention of `<system_instruction>`
 * (e.g. a chat discussing this very behavior) is never touched. The raw line
 * is always preserved in `raw_json`.
 */

// A leading <system_instruction>…</system_instruction> or the hyphen variant.
// The backreference \1 forces the close tag to match the open tag exactly.
const LEADING_INSTRUCTION_BLOCK = /^\s*<(system[_-]instruction)\s*>[\s\S]*?<\/\1\s*>/i;

// A leading line that is solely an attachment path — Conductor pastes these as
// `/tmp/attachments/…` or `…/.context/attachments/…` before the real prompt.
const LEADING_ATTACHMENT_PATH = /^\s*\/\S*attachments\/\S+[ \t]*\r?\n?/i;

// claude-mem observer sessions: every user message is a wrapper around the
// primary session's real request. Anchored at the start so a normal sentence
// mentioning "observe" is never matched.
const OBSERVER_SIGNATURE = /^\s*(Hello memory agent,\s*you are continuing to observe|<observed_from_primary_session>)/i;
const USER_REQUEST = /<user_request>([\s\S]*?)<\/user_request>/i;

// Slash-command echoes Claude Code writes as the first "user" turn.
const COMMAND_ECHO = /^\s*<command-(name|message|args)>/i;

// Claude Code prepends a <local-command-caveat>…</local-command-caveat> block to slash-command /
// local-command turns ("Caveat: The messages below were generated by the user while running local
// commands…"). The real prompt/command follows it. Anchored at the start, non-greedy close.
const LEADING_CAVEAT = /^\s*<local-command-caveat>[\s\S]*?<\/local-command-caveat>\s*/i;

// Compaction continuation: the whole turn is "This session is being continued from a previous
// conversation…" boilerplate plus an auto-generated summary — there is no real user ask to surface.
const LEADING_CONTINUATION = /^\s*This session is being continued from a previous conversation\b[\s\S]*$/i;

export function cleanPromptText(text: string): string {
  // Strip a leading local-command caveat block first; the real prompt/command follows it.
  let s = text.replace(LEADING_CAVEAT, "").replace(/^\s+/, "");
  // A truncated/unclosed caveat — a registry session name cut off mid-boilerplate, so the open tag
  // has no matching close and no real content after it — leaves nothing usable to surface.
  if (/^<local-command-caveat\b/i.test(s)) return "";

  // Observer boilerplate → surface the observed <user_request> (or nothing).
  if (OBSERVER_SIGNATURE.test(s)) {
    const m = s.match(USER_REQUEST);
    return m && m[1]!.trim() ? m[1]!.replace(/\s+/g, " ").trim() : "";
  }

  // Slash-command echoes → surface the command (e.g. "/insights"). Anchored.
  if (COMMAND_ECHO.test(s)) {
    const name = s.match(/<command-name>([\s\S]*?)<\/command-name>/i);
    if (name && name[1]!.trim()) return name[1]!.trim();
    const msg = s.match(/<command-message>([\s\S]*?)<\/command-message>/i);
    if (msg && msg[1]!.trim()) {
      const m = msg[1]!.trim();
      return m.startsWith("/") ? m : "/" + m;
    }
    return "";
  }

  // Compaction continuation preamble → no real ask to show.
  if (LEADING_CONTINUATION.test(s)) return "";

  let prev: string;
  do {
    prev = s;
    s = s.replace(LEADING_INSTRUCTION_BLOCK, "");
    s = s.replace(LEADING_ATTACHMENT_PATH, "");
    s = s.replace(LEADING_CAVEAT, "");
  } while (s !== prev);
  return s.trim();
}

/**
 * A clean, single-line session title from a raw `name`. Claude Code sometimes sets a session's
 * name to a raw first message that still carries caveat / continuation / command boilerplate;
 * this strips it and collapses whitespace. Returns "" when nothing real remains, so callers can
 * fall back to a short id or the cwd basename.
 */
export function cleanSessionName(name: string | null | undefined): string {
  if (!name) return "";
  return cleanPromptText(name).replace(/\s+/g, " ").trim();
}
