import { describe, it, expect } from "vitest";
import { cleanPromptText, cleanSessionName } from "./clean-prompt";

describe("cleanPromptText — local-command caveat", () => {
  it("strips a leading caveat block and surfaces the command echo", () => {
    const t = `<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these…</local-command-caveat>\n<command-name>/compact</command-name>`;
    expect(cleanPromptText(t)).toBe("/compact");
  });
  it("strips a leading caveat block and surfaces following user text", () => {
    const t = `<local-command-caveat>Caveat: …</local-command-caveat>\n\nFix the build please`;
    expect(cleanPromptText(t)).toBe("Fix the build please");
  });
  it("returns empty for a truncated/unclosed caveat (registry name cut mid-boilerplate)", () => {
    const t = "<local-command-caveat>Caveat: The messages below were generated by the user while running local co";
    expect(cleanPromptText(t)).toBe("");
  });
});

describe("cleanPromptText — compaction continuation", () => {
  it("returns empty for a continuation preamble (pure boilerplate)", () => {
    const t = "This session is being continued from a previous conversation that ran out of context. The summary below covers…";
    expect(cleanPromptText(t)).toBe("");
  });
});

describe("cleanSessionName", () => {
  it("collapses whitespace, keeps real names, drops boilerplate", () => {
    expect(cleanSessionName("  code-visualization-sync-panel  ")).toBe("code-visualization-sync-panel");
    expect(cleanSessionName("This session is being continued from a previous conversation that ran out of context.")).toBe("");
    expect(cleanSessionName(null)).toBe("");
  });
});
